### ISSUE TITLE
BUNDLE: Build a snap distribution for the app

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattleng#15]
# Description

Set up the snapcraft files to build a snap bundle of the app for distribution

# Why

To support easy installation on Linux and so encourage use and feedback while we progress with development.

# Closing Criteria
 
- [ ] Standalone bundle for this Linux successfully built as a snap package: `rattleng.snap`

**Comment by gjwgit** [comment]
# Basics

```
$ flutter build linux
$ ls build/linux/x64/release/bundle/
total 32K
 24K rattleng*  4.0K data/  4.0K lib/
```

# Install By Hand

Create a script `rattleng`

```bash
#!/bin/bash

~/projects/rattleng/build/linux/x64/release/bundle/rattleng
```

Then `chmod a+rx rattleng`.

Then `./rattleng`

**Comment by gjwgit** [comment]
# Package Using Snap

https://docs.flutter.dev/deployment/linux

1. Create `snap/snapcraft.yaml`, `snap/gui/bstim.desktop`, `snap/gui/bstim.png`.
2. Run `snapcraft` from the root of the project
3. For a local machine install `snap install rattleng.snap`

The build from `snapcraft` can take some time, setting up a VM to do the build.

**Comment by gjwgit** [comment]
Currently failing to build.

```
$ snapcraft
```

Then

```
[...]
[  +58 ms] Building Linux application...
[  +11 ms] executing: [build/linux/x64/release/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DFLUTTER_TARGET_PLATFORM=linux-x64
/root/parts/rattle/build/linux
[ +498 ms] CMake Error: The current CMakeCache.txt directory /root/parts/rattle/build/build/linux/x64/release/CMakeCache.txt is different than the
directory /home/gjw/git/github/gjwgit/rattle/build/linux/x64/release where CMakeCache.txt was created. This may result in binaries being created in
the wrong place. If you are not sure, reedit the CMakeCache.txt
[   +9 ms] CMake Error: The source "/root/parts/rattle/build/linux/CMakeLists.txt" does not match the source
"/home/gjw/git/github/gjwgit/rattle/linux/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
[  +85 ms] Building Linux application... (completed in 593ms)
[        ] "flutter linux" took 1,196ms.
[   +3 ms] Unable to generate build files
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runCmake (package:flutter_tools/src/linux/build_linux.dart:154:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:76:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:89:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1323:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:113:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +128 ms] ensureAnalyticsSent: 122ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
Failed to run 'flutter build linux --release -v -t lib/main.dart' for 'rattle': Exited with code 1.
Verify that the part is using the correct parameters and try again.
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
```

**Comment by gjwgit** [comment]
Do a clean first to ensure it works:

```
flutter clean
snapcraft clean rattle
snapcraft
```

**Comment by gjwgit** [comment]
Can now again regenerate the snap. But on install getting 

```
2024-08-04T07:33:30+10:00 INFO snap "rattle" has bad plugs or slots: system-files (cannot add system-files plug: "$SNAP/usr/lib/R" must start with "/")
Automatically connect eligible plugs and slots of snap "rattle"                                                                                                    |
2024-08-04T07:35:02+10:00 INFO snap "rattle" has bad plugs or slots: system-files (cannot add system-files plug: "$SNAP/usr/lib/R" must start with "/")
rattle 6.2.31 installed
WARNING: There is 1 new warning. See 'snap warnings'.
```

- [x] Need to remove the $SNAP
- [x] Test

**Comment by gjwgit** [comment]
The snap install works from `/snap/rattle/current/rattle` but not the default `/snap/bin/rattle`

```
gjw@rattleecosyslnet:~$ /snap/bin/rattle 
Gtk-Message: 10:39:05.809: Failed to load module "appmenu-gtk-module"
X11 connection rejected because of wrong authentication.

(rattle:873351): Gtk-WARNING **: 10:39:05.909: cannot open display: localhost:10.0
gjw@rattleecosyslnet:~$ /snap/rattle/current/rattle 
```

**Comment by gjwgit** [comment]
When running from /snap/bin/rattle the R process does not initate: `execvp: No such file or directory`

Perhaps the packaging of R inside the snap is not working or is not finding the installed location of R as specified  in `lib/providers/pty.dart`.

- [X] Try commenting out the system-files plug from `pubspec.yaml` and rebuild the snap to understand the behaviour. NO CHANGE both startups the same - /snap/bin/rattle fails to start R and /snap/rattle/current/rattle loaded just fine.
- [X] Try replacing /usr/bin/R with just R. No change to the situation. Restore /usr/bin/R.
- [X] Could it be that we should not depend on r-recommended in the snap? Would be best to do so as a standalone app but remove it for now as it seems not to have any effect. I remove the dependency and no change.

**Next step is to explore the snap documentation more carefully.**

![Image](https://github.com/user-attachments/assets/e959858b-857c-4a93-92ab-0139538103fa)
