### ISSUE TITLE
WORDCLOUD: Review how image is displayed/updated to ensure working on Linux

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattleng#97]
## Description

Currently the wordcloud image display is not being updated on Linux though said to work on MacOS.

After a BUILD we see:

![Image](https://github.com/gjwgit/rattleng/assets/1681429/db5c21d5-5738-491f-a56e-0341eb6759f6)

The image is refreshed on going to another tab and returning

![Image](https://github.com/gjwgit/rattleng/assets/1681429/06361a51-32ef-4aa5-a877-1ac924da568b)

The exception:

```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack:
#0      _futurize (dart:ui/painting.dart:6980:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:6786:12)
#2      instantiateImageCodecWithSize (dart:ui/painting.dart:2290:60)
#3      PaintingBinding.instantiateImageCodecWithSize (package:flutter/src/painting/binding.dart:141:15)
#4      MemoryImage._loadAsync (package:flutter/src/painting/image_provider.dart:1576:18)
<asynchronous suspension>
#5      MultiFrameImageStreamCompleter._handleCodecReady
(package:flutter/src/painting/image_stream.dart:1005:3)
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by gjwgit** [comment]
Introduce a work around of waiting for the file to have content by trying to read it every second.

**Comment by gjwgit** [comment]
Completed as a89d7df5991bde967ecd85e547b713f13cf60734
